USE proyectotienda;

-- PROCEDURE PARA AÑADIR ARTICULOS A LA BASE DE DATOS
DELIMITER |
CREATE procedure spInsertarArticulos (
	ID_ARTICULO INT(11),
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(500),
    PRECIO DECIMAL(10,2),
    STOCK INT,
    CATEGORIA_ID INT,
    TIPO_ARTICULO VARCHAR(500)
)
BEGIN 
INSERT INTO ARTICULOS(ID_ARTICULO ,NOMBRE ,DESCRIPCION,PRECIO,STOCK,CATEGORIA_ID,TIPO_ARTICULO)
	VALUES(ID_ARTICULO ,NOMBRE ,DESCRIPCION,PRECIO,STOCK,CATEGORIA_ID,TIPO_ARTICULO);

END |
DELIMITER ;
-- PROCEDURE PARA MODIFICAR ARTICULOS DE LA BASE DE DATOS 
DELIMITER |
CREATE procedure spModificarArticulos(
	pID_ARTICULO INT,
    pNOMBRE VARCHAR(100),
    pDESCRIPCION VARCHAR(500),
    pPRECIO DECIMAL(10,2),
    pSTOCK INT,
    pCATEGORIA_ID INT,
    pTIPO_ARTICULO VARCHAR(500)
)
BEGIN
UPDATE articulos SET NOMBRE=pNOMBRE,DESCRIPCION=pDESCRIPCION,
	PRECIO=pPRECIO,STOCK=pSTOCK,CATEGORIA_ID=pCATEGORIA_ID,TIPO_ARTICULO=pTIPO_ARTICULO WHERE ID_ARTICULO=pID_ARTICULO;
END |
DELIMITER ;
-- AÑADIR USUARIO 
DELIMITER |
CREATE procedure spaddUsuario (
in CODIGO_USUARIO INT ,
in NOMBRE_USUARIO VARCHAR(100),
in NOMBRE VARCHAR(100),
in APELLIDO VARCHAR(100),
in CORREO VARCHAR(100),
in CONTRASEA VARCHAR(100)
)
BEGIN 
INSERT INTO USUARIO(NOMBRE_USUARIO,NOMBRE,APELLIDO,CORREO,CONTRASEA)
	VALUES(NOMBRE_USUARIO ,NOMBRE,APELLIDO,CORREO,CONTRASEA);

END |
DELIMITER ;

