CREATE DATABASE ProyectoTienda;
USE PROYECTOTIENDA;

CREATE TABLE USUARIO(
ID_USUARIO INT PRIMARY KEY auto_increment,
NOMBRE_USUARIO VARCHAR(100)NOT NULL,
NOMBRE VARCHAR(100)NOT NULL,
APELLIDO VARCHAR(100)NOT NULL,
CORREO VARCHAR(100)NOT NULL,
CONTRASEA VARCHAR(100)NOT NULL
);

CREATE TABLE ARTICULOS(
ID_ARTICULO INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION varchar(500),
PRECIO DECIMAL(10,2) DEFAULT 0.00,
STOCK INT default 0,
CATEGORIA_ID INT NOT null,
TIPO_ARTICULO VARCHAR(500)
);
CREATE TABLE VENTAS(
ID_VENTA INT PRIMARY KEY AUTO_INCREMENT,
NUMERO_FACTURA INT  NOT NULL,
COMPRADOR VARCHAR(30) NOT NULL,
FECHA_VENTA DATETIME NOT NULL DEFAULT NOW(),
GANANCIAS INT NOT NULL
);
CREATE TABLE COMPRAS(
ID_COMPRA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ARTICULO_ID INT NOT NULL,
UNIDADES_COMPRADAS INT NOT NULL,
FECHA_COMPRA DATETIME NOT NULL
);


